# Generated by Django 4.1 on 2023-12-02 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_imie', models.CharField(max_length=30)),
                ('usr_nazwisko', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='KntKarty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knt_nazwa', models.CharField(max_length=50, unique=True)),
                ('knt_tel', models.CharField(max_length=12)),
                ('knt_email', models.CharField(max_length=40, unique=True)),
                ('knt_create_date', models.DateTimeField(default=datetime.datetime(2023, 12, 2, 16, 25, 16, 230390))),
                ('knt_lastmod_date', models.DateTimeField()),
                ('knt_create_userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Slowniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slw_akronim', models.CharField(max_length=5)),
                ('slw_nazwa', models.CharField(max_length=50)),
                ('slw_typ', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiz_typ', models.IntegerField()),
                ('wiz_data', models.DateTimeField()),
                ('wiz_opis', models.CharField(max_length=255)),
                ('wiz_kntid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kntkarty')),
                ('wiz_usrid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.appuser')),
            ],
        ),
    ]
