# Generated by Django 4.1 on 2023-12-02 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_kntkarty_knt_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kntkarty',
            name='knt_create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 16, 30, 38, 684188)),
        ),
        migrations.AlterField(
            model_name='kntkarty',
            name='knt_email',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='kntkarty',
            name='knt_lastmod_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 16, 30, 38, 684188)),
        ),
    ]
