# Generated by Django 4.1 on 2023-12-06 18:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_kntkarty_knt_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kntkarty',
            name='knt_create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 19, 17, 27, 925223)),
        ),
        migrations.AlterField(
            model_name='kntkarty',
            name='knt_lastmod_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 19, 17, 27, 925223)),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='wiz_typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.slowniki'),
        ),
    ]
