# Generated by Django 4.1 on 2023-12-09 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_slowniki_slw_typ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kntkarty',
            name='knt_create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 22, 54, 2, 600658)),
        ),
        migrations.AlterField(
            model_name='kntkarty',
            name='knt_lastmod_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 22, 54, 2, 600658)),
        ),
    ]
